use_frameworks!

platform :ios, '11.0'

target 'MobilliumQRCodeReader_Example' do
  pod 'MobilliumQRCodeReader', :path => '../'

  target 'MobilliumQRCodeReader_Tests' do
    inherit! :search_paths

    
  end
end
